language: c
sudo: false
dist: trusty
branches:
  except:
  - gh-pages
cache:
  directories:
  - $HOME/.opam
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
    - aspcud
    - debianutils
    - libffi-dev
    - libgmp-dev
    - libpcre3-dev
    - m4
    - perl
    - pkg-config
    - tzdata
    - zlib1g-dev
install: scripts/install
script: scripts/build
